### PR TITLE
Adding ability to use SoftwareSerial

### PR DESCRIPTION
**Pull request by pbaja**
Hello!

Thank you for creating this amazing library, after hours of testing other libraries this is a first one that actually worked on my ESP8266 (after some minor changes that i am sharing right now in this pull request).

It works flawlessly on the latest firmware (FW 3.51) except for that "ampHours" and "ampHoursCharged" always show 0. I will try to investigate it further today - but maybe you have any idea why this is broken? Or i did something wrong.

 Thank you again for your work.

### CODE REVIEW

**Comment by SolidGeek** [comment]
Hey mate, thanks for your pull request. Actually, I have been wanting to implement and test this for quite some time. I guess this issue is fixed now https://github.com/SolidGeek/VescUart/issues/1

**Comment by pbaja** [comment]
I didn't really checked if these values (ampHours and ampHoursCharged) are fixed now because i just put my ESP into a case and disoldered programming wires. I will check that maybe this weekend and let you know :)

**Comment by pbaja** [comment]
Hi,

I just confirmed that after my changes both ampHours, ampHourCharged and wattHours, wattHoursCharged are working and displaying values :) Everything works like a charm.

**Comment by SolidGeek** [comment]
That is great, thanks for validating the update! I have merged your pull-request to the development branch  👍

**Pull request merged**
